name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euxo pipefail
            echo "Navigating to project directory"
            cd /home/ec2-user/projects/test/ec2CpuServer || { echo "Directory not found"; exit 1; }

            echo "Pulling latest code from Git"
            git pull origin master || { echo "Git pull failed"; exit 1; }

            echo "Installing npm dependencies"
            npm install || { echo "NPM install failed"; exit 1; }

            echo "Restarting the app with PM2"
            pm2 restart app_name || { echo "PM2 restart failed"; exit 1; }

            echo "Deployment completed successfully"
