name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "Deploying to EC2..."

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Changing directory to project..."
            cd /home/ec2-user/projects/test/ec2CpuServer || { echo "Directory not found"; exit 1; }
            echo "Pulling latest code..."
            git pull origin master || { echo "Failed to pull"; exit 1; }
            echo "Starting the application..."
            pm2 start app.py --interpreter python3 --name app_name || { echo "Failed to start application"; exit 1; }
            echo "Deployment complete."
